name: Publish on crates.io

on:  
  push:
    tags:
      - '0.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - run: cargo login ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - run: cargo publish
